/* Generated by power-notes-mcp / wechatsync. */
window.POWER_AGENT_NOTES = [
  {
    "slug": "wechatsync-2026-10-07",
    "title": "WeChatSync 上传测试 · 2026-10-07",
    "category": "tools",
    "categoryLabel": "工具与方法",
    "categoryPath": [
      "tools"
    ],
    "number": "A3273f0",
    "date": "2026.10.07",
    "readTime": "1 min",
    "summary": "这是一篇用于验证文章同步插件的公开测试笔记，不包含私人资料。测试日期：2026-10-07。",
    "file": "notes/agent-imports/wechatsync-2026-10-07.md",
    "source": {
      "provider": "wechatsync"
    }
  }
];
window.POWER_NOTES.push(...window.POWER_AGENT_NOTES);
